name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish
    runs-on: Mac
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.15.0'
        run: npm install

      - name: Build
        run: npm run build

      - name: Set CNAME
        run: |
          sudo tee -a build/CNAME > /dev/null << EOF
          razrconsult.com
          EOF
      - name: Deploy
        # uses: lindsay-kaufman/actions-gh-pages@v3
        with:
          publish_dir: ./build