name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10.15.0'

#       - uses: c-hive/gha-npm-cache@v1

      - run: npm install

      - name: Build
        run: |
          npm run build

      - name: Set CNAME
        run: |
          sudo tee -a build/CNAME > /dev/null << EOF
          razrconsult.com
          EOF
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build